language: go

go:
  - tip

branches:
  only:
  # - master
  - test

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v 
  - $GOPATH/bin/goveralls -service=travis-ci