language: go

go:
  - tip

branches:
  only:
  # - master
  - test

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken "9kZOZwQhGLBmuzrrbCQOk2dzXKxlMoPZL"